### PR TITLE
Align with npm spec for "main"

### PR DESCRIPTION
**Pull request by dgsmith2**
https://docs.npmjs.com/files/package.json#main

### CODE REVIEW

**Comment by niemyjski** [comment]
Can you bump the version down to 5.3.0, we've yet to release it so npm or bower won't pick it up until we create a release.

**Comment by niemyjski** [comment]
Could you also merge in these changes :) https://github.com/m-e-conroy/angular-dialog-service/pull/141

**Comment by niemyjski** [comment]
@dgsmith2 can you also merge this in: https://github.com/m-e-conroy/angular-dialog-service/pull/152 if the changes make sense.

**Comment by dgsmith2** [comment]
@niemyjski, no clue if I did the merges correctly in the context of Github and PRs.

I added the other 2 forks as remotes and merged in the latest commits from the referenced PRs.

**Comment by niemyjski** [comment]
@dgsmith2 thanks! If it looks good to you let me know and I'll merge it. I use this without requirejs / node so I can't really test this change too much.

**Comment by dgsmith2** [comment]
@niemyjski, best I can tell it is working fine for me.

We just are making the move from Bower to npm.  Our first stab is manually specifying the necessary files in `node_modules/...`.  So, I can't speak just yet to the likes of using any of the client-side packaging tools.

**Comment by niemyjski** [comment]
Thank you!

**Pull request merged**
