### PR TITLE
Updated npm and bower dependencies. Corrected license reference. Included bower_components into .gitignore file.

### PR DESCRIPTION
**Pull request by dennybiasiolli**

### CODE REVIEW

**Comment by dougmoscrop** [comment]
LGTM, @m-e-conroy I'm yet to use my merge permissions on this repo.. I would here, though I'm concerned that we don't have tests.

@dennybiasiolli have you manually tested this?

**Comment by dennybiasiolli** [comment]
@dougmoscrop not yet, I've only update dependencies and correct license and .gitignore.

**Comment by m-e-conroy** [comment]
@dougmoscrop I'll trust your judgement as my time is limited.  Maybe someone can create some tests?

I'm with you though, this should be merged.  Perhaps - merge it, the releases are still viable - the master branch will just be a work in progress... If someone has time for some tests, then we can create a new release later.  What do you think?

**Comment by dougmoscrop** [comment]
I'll try to poke around a bit at it before I merge.

**Comment by wcomartin** [comment]
I'd be up for creating unit tests, anybody opposed to karma/jasmine?

also, i would like to setup a gulp watch task with a http connect server.

**Comment by m-e-conroy** [comment]
Go for it.

On Tue, Oct 13, 2015 at 4:55 PM, William Comartin <notifications@github.com>
wrote:

> I'd be up for creating unit tests, anybody opposed to karma/jasmine?
>
> also, i would like to setup a gulp watch task with a http connect server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-e-conroy/angular-dialog-service/pull/141#issuecomment-147850892>
> .
>



-- 
Michael E. Conroy
michael.e.conroy@gmail.com

Blog: http://michaeleconroy.blogspot.com/
GitHub: https://github.com/m-e-conroy
LinkedIn Profile
<https://www.linkedin.com/profile/view?id=260227&trk=nav_responsive_tab_profile>

**Comment by wcomartin** [comment]
I've started creating tests in this repo https://github.com/wcomartin/angular-dialog-service/tree/UnitTests

I've also added a examples_live folder for the gulp-connect serving directory, because i didn't want to overwrite the current examples folder

**Comment by m-e-conroy** [comment]
Sounds good to me, I appreciate the help - especially since my time has
been lacking lately.

On Tue, Oct 13, 2015 at 11:15 PM, William Comartin <notifications@github.com
> wrote:

> I've started creating tests in this repo
> https://github.com/wcomartin/angular-dialog-service/tree/UnitTests
>
> I've also added a examples_live folder for the gulp-connect serving
> directory, because i didn't want to overwrite the current examples folder
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/m-e-conroy/angular-dialog-service/pull/141#issuecomment-147915134>
> .
>



-- 
Michael E. Conroy
michael.e.conroy@gmail.com

Blog: http://michaeleconroy.blogspot.com/
GitHub: https://github.com/m-e-conroy
LinkedIn Profile
<https://www.linkedin.com/profile/view?id=260227&trk=nav_responsive_tab_profile>

**Comment by niemyjski** [comment]
@wcomartin let me know when the tests are ready and I'll run them as well and merge it

**Comment by niemyjski** [comment]
@wcomartin any updates on this? Can you please merge in latest and resolve conflicts. We recently updated the dependencies.

**Comment by niemyjski** [comment]
closed via: https://github.com/m-e-conroy/angular-dialog-service/pull/168

**Pull request closed without merging**
