### PR TITLE
Updating to UI-Bootstrap 0.14.2, which includes renaming $modal to $uibModal

### PR DESCRIPTION
**Pull request by NealHaggard**
Note that in 0.14.3, they will also be renaming $modalInstance to $uibModalInstance, so another change will need to be made when that is released.  Solves m-e-conroy/angular-dialog-service/issues/145

### CODE REVIEW

**Comment by NealHaggard** [comment]
UI-Bootstrap 0.14.3 has been published, so updated to also rename $modalInstance to $uibModalInstance.

**Comment by niemyjski** [comment]
@m-e-conroy @NealHaggard does it make sense to even support 1.3 anymore? 1.4.7 is out and 1.5 is on the verge of release. Would be nice to update all the dependencies to 1.4.7 too.

**Comment by NealHaggard** [comment]
We just upgraded to 1.4.7 this week, we were previously following 1.3.  Mainly because we haven't had breathing time to update.  I'm not sure there are any issues with leaving support for Angular 1.3.  My changes have all been related to UI-Bootstrap's 0.14 version, which still supports Angular 1.3 and 1.4.

**Comment by Tim-Erwin** [comment]
+1 for this change

**Comment by dougmoscrop** [comment]
Maybe we could get few a through of the other PRs, release a version, then move on to this?

**Comment by niemyjski** [comment]
I need this change as well before I can upgrade to the new version. I have logging in my app that sends to a third party service (https://github.com/exceptionless/Exceptionless) and I get like 30 warning messages per client.

**Comment by niemyjski** [comment]
@dougmoscrop @m-e-conroy I don't see anything wrong with this commit on why it shouldn't be merged. If the consensus is to merge it I can click the button.

**Comment by dougmoscrop** [comment]
The commit itself looks fine to me too. I'm :+1: for you to merge but wish we had Travis or something set up so the tests would be run.

**Comment by niemyjski** [comment]
I'm going to merge this and test as well. Can you all do this as well.

**Comment by m-e-conroy** [comment]
Yeah, I think we should update to support newest versions.  Actually only
noticed the name changes in Ui-bootstrap this past week.

**Pull request merged**
